### PR TITLE
Add push/set JSON with String parameter

### PR DESCRIPTION
**Pull request by Gizmodo**

### CODE REVIEW

**Comment by mobizt** [comment]
I remove this JSON string support since v 2.6.x as I state in the doc [here](https://github.com/mobizt/Firebase-ESP8266#changes-from-earlier-version)

**Comment by Gizmodo** [comment]
Why did decide to remove them?

**Comment by mobizt** [comment]
Better and alternative to use **FirebaseJson** which already has function **setJsonData** if someone want to set JSON string to it. And due to I want to remove the setXXX, pushXXX and getXXX to use the generic (template) function as simple set, push and get which String parameters of JSON string is not consistent between get and push or set.

**Comment by Gizmodo** [comment]
Thank you. Close PR.

**Pull request closed without merging**
